---
env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules:
  semi: ['error', 'never']
  quotes: ['error', 'single']
  indent: ['error', 2]
  no-unused-vars: ['warn']
  no-console: 'off'
  eqeqeq: ['error', 'always']
